### ISSUE TITLE
Betriebsmodus 

### ISSUE THREAD

**Issue by GO74** [BjoernLange/openhab-miele-cloud-binding-beta#21]
# Expected Behavior
Betriebsmodus should signal 'OFF'

# Actual Behavior
Betriebsmodus signals 'Off' - with lowercase 'f'

# Environment
G7110 - openHAB 4.0.3 - Miele Binding 4.0.3

**Comment by BjoernLange** [comment]
> Betriebsmodus signals 'Off' - with lowercase 'f'

Which channel is linked to the item displaying this?

**Comment by GO74** [comment]
The value is coming from the channel 'operation_state'.

**Comment by BjoernLange** [comment]
`operation_state` shows the human readable value intended for displaying on user interfaces. Therefore, this is a reasonable value and the intended behavior.
