### ISSUE TITLE
Feature request: Washing Machine Energy and Water consumption

### ISSUE THREAD

**Issue by martink2** [BjoernLange/openhab-miele-cloud-binding-beta#6]
# What do you want to achieve? Is your feature request related to a problem?
For my Miele washing machine i would like to monitor the amount of energy and water consumed during a washing cycle,
in the Miele app i can see the information while the program is running and hidden inside the device ui i can find the consumption levels for the last run cycle. I was hoping for the binding to also expose the data so I can store the values for analysis and adjusting of washing habits to get the best efficiency for my usage.

# Describe the solution you'd like
I would like new channels to expose the data (Energy in kwh consumed, Water in liters consumed) to Openhab same as the iOS app does.

# Describe alternatives you've considered
Power metering devices between the plug and the device and same for water inlet but that would be a big invest that seems useless given the data is already present on the washing machine.

**Comment by ABernie123** [comment]
I second that. 
I realize this info is not exposed via the Miele-API at the moment, but it would be very useful indeed.

**Comment by BertP** [comment]
Thank you for your suggestion, this feature is already supported by the Miele 3rd Party API but will not be integrated within the first version of the Miele-Cloud binding.
From our point of view the feature set of the binding was defined with the publishing of the beta release. 
We see the binding as a starting point supported by Miele and may add this feature in the future but it could take some time. If you want to have it faster feel free to contribute once the binding was initially contributed.

**Comment by BjoernLange** [comment]
This has been implemented in the meantime.
