### ISSUE TITLE
Bug report: temperature_target channel is empty for dishwashers

### ISSUE THREAD

**Issue by BjoernLange** [BjoernLange/openhab-miele-cloud-binding-beta#9]
Split from original report by @sirupflex in #5.

# Expected Behavior

When I start a program on my dishwasher, I expect to see information regarding the program temperature.

# Actual Behavior

When I start a program on my dishwasher, I do not get any data on the temperature_target channels.

# Environment

Binding version: v1.0.0-beta.1
openHAB version: 2.5.6
Running on: docker (QNAP Container Station)
Involved Miele devices: Dishwasher G7315

# Steps to Reproduce

- Turn on the dishwasher, start a program (e.g. "Auto", in my case)
- Check the data for the channels elapsed_time and temperature_target (no data visible)

# Possible Solution

Send the value from the cloud to the channel in the `ThingHandler`.

**Comment by BjoernLange** [comment]
After further analysis I figured out that the value of the channel is actually set by the binding, but the cloud is not delivering any value (see @sirupflex's post in #5 for the raw json):
```json
"targetTemperature": [
    {
        "value_raw": -32768,   # means: not present
        "value_localized": null,
        "unit":"Celsius"
    }, {
        "value_raw": -32768,
        "value_localized": null,
        "unit": "Celsius"
    }, {
        "value_raw": -32768,
        "value_localized": null,
        "unit": "Celsius"
    }]
```

@sirupflex: Please check whether the channel is populated prior to starting the dishwasher, i.e. when the program was selected but the dishwasher not actually started.

**Comment by BjoernLange** [comment]
We had a meeting with Miele and they clarified that dishwashers do not support the target temperature. Sorry for the inconvenience. Thus we are going to remove the `temperature_target` channel from dishwasher devices.

**Comment by sirupflex** [comment]
Thanks for the info @BjoernLange

**Comment by BjoernLange** [comment]
Rolled out with [Beta Version 2](https://github.com/BjoernLange/openhab-miele-cloud-binding-beta/releases/tag/v1.0.0-beta.2).
